server:
  port: 8902
spring:
  application:
    name: hystrix1demo
  config:
    name: hystrix1demo
security:
  ignored: true
turbine:
  aggregator:
    clusterNameExpression: 'default'
  appConfig: ms1demo,ms11demo
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${server.port}