endpoints:
  shutdown:
    enabled: true
    
server:
  port: 8904

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/opando/archaius1demo-config/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/