server:
  port: 8910
endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8901/eureka/
spring:
   config:
      name:  ms1demo
   application:
      name:  ms1demo 